#! /bin/bash

# Deploys a githole repository here

# Drop the githole scripts (including this one) into a folder named '.githole'
# inside your githole repository, and run this deploy script.

# Put the sync command in an hourly cron
echo "Putting sync commands in an hourly cron job..."
sudo ln -s $(pwd)/sync /etc/cron.hourly

# Symlink the sync command in the bin directory so we can force syncs
echo "Symlinking sync to /usr/bin/..."
sudo ln -s $(pwd)/sync /usr/bin/githolesync

# Put this .githole directory in the .gitignore so it doesn't get added
echo ".githole" >> ../.gitignore

