#! /bin/bash

# Deploys a client githole repository

# Client deploy instructions
# --------------------------
#
# 1. Clone your master githole repo onto your client machine
# 2. Drop these githole scripts (including this one) into a folder named 
#    '.githole' inside your client githole repository you just cloned, and run 
#    this deploy script.
#
# (See README for more details)

# Put the sync command in an hourly cron
echo "Putting sync commands in an hourly cron job..."
sudo ln -s $(pwd)/sync /etc/cron.hourly
