#! /bin/bash

# Synchronize the specified githole repo at the specified interval
#
# Usage:
#     githole <path to githole repository> <interval (seconds) between syncs>
# 
# Example:
#     githole ~/mygithole 300  # Sync "mygithole" every 5 minutes

# Collect command line args
REPO=$1
INTERVAL=$2

function main {
    # "Main" function. Runs after script is fully loaded.
    echo "---------"
    echo " githole "
    echo "---------"
    echo "Press Ctrl+c to exit."
    while [ true ]
    do
        echo -n "Synchronizing githole repo $REPO..."
        sync
        echo "Done! Waiting $INTERVAL seconds..."
        sleep $INTERVAL
    done
}

function sync {
    # Synchronize the specified githole repository
    cd $REPO
    git pull origin master
    git add *
    git commit -am "Cha-cha-changes!"
    git push origin master
}

main